/* 
 * File:   engine_common.h
 * Author: cl
 *
 * Created on June 10, 2011, 8:38 PM
 */

#ifndef ENGINE_COMMON_H
#define	ENGINE_COMMON_H

#define COLOR_TEXTURE_UNIT              GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX        0
#define SHADOW_TEXTURE_UNIT             GL_TEXTURE1
#define SHADOW_TEXTURE_UNIT_INDEX       1
#define NORMAL_TEXTURE_UNIT             GL_TEXTURE2
#define NORMAL_TEXTURE_UNIT_INDEX       2
#define RANDOM_TEXTURE_UNIT             GL_TEXTURE3
#define RANDOM_TEXTURE_UNIT_INDEX       3
#define DISPLACEMENT_TEXTURE_UNIT       GL_TEXTURE4
#define DISPLACEMENT_TEXTURE_UNIT_INDEX 4



#define AGENT_VORONOI_TEXTURE_UNIT      GL_TEXTURE0
#define AGENT_VORONOI_TEXTURE_UNIT_INDEX      0

#define MARKER_SAMPLING_TEXTURE_UNIT    GL_TEXTURE1
#define MARKER_SAMPLING_TEXTURE_UNIT_INDEX    1

#define MARKER_TEXTURE_WRITE_UNIT             GL_TEXTURE3
#define MARKER_TEXTURE_WRITE_UNIT_INDEX       3




#define MOTION_TEXTURE_UNIT             GL_TEXTURE1
#define MOTION_TEXTURE_UNIT_INDEX             1

#define MOTION_TEXTURE_WRITE_UNIT             GL_TEXTURE2
#define MOTION_TEXTURE_WRITE_UNIT_INDEX             2

#define MOTION_NAVI_ARRAY_UNIT             GL_TEXTURE3
#define MOTION_NAVI_ARRAY_UNIT_INDEX             3


#define FINAL_AGENT_VORONOI_TEXTURE_UNIT      GL_TEXTURE0
#define FINAL_AGENT_VORONOI_TEXTURE_UNIT_INDEX      0

#define FINAL_MOTION_TEXTURE_UNIT             GL_TEXTURE4
#define FINAL_MOTION_TEXTURE_UNIT_INDEX             4

#define FINAL_MOTION_TEXTURE_WRITE_UNIT             GL_TEXTURE3
#define FINAL_MOTION_TEXTURE_WRITE_UNIT_INDEX            3

#define FINAL_DENSITY_TEXTURE_WRITE_UNIT             GL_TEXTURE1
#define FINAL_DENSITY_TEXTURE_WRITE_UNIT_INDEX             1

#define FINAL_DENSITY_TEXTURE_BUFFER_WRITE_UNIT             GL_TEXTURE2
#define FINAL_DENSITY_TEXTURE_BUFFER_WRITE_UNIT_INDEX             2

#endif	/* ENGINE_COMMON_H */

